### ISSUE TITLE
great stuff, but i have one small issue, please help!

### ISSUE THREAD

**Issue by sawise** [madhu314/sectionedgridview#2]
Hi.
Your gridview is great, just what i was looking for!
I just have issue with removing one specific item from the list. I can only remove a whole section. The problem is that the whole section has the same key, but i dont have any idea how to get the specific item ID.  Do you have any good ideas?

BR
Sam

**Comment by madhu314** [comment]
Hey...I have not planned for such a feature..this code is just a demonstration of using list adapter smartly to create sections akin to gridview
